# backend/main_simple.py
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import re
import logging
from datetime import datetime
import requests

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="YouTube Simple Analyzer", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class VideoAnalysisRequest(BaseModel):
    video_url: str

class VideoAnalysisResponse(BaseModel):
    success: bool
    analysis: Optional[str] = None
    error: Optional[str] = None
    video_id: Optional[str] = None
    video_title: Optional[str] = None

def extract_video_id(url: str) -> str:
    patterns = [
        r'(?:youtube\.com\/watch\?v=)([\w-]+)',
        r'(?:youtu\.be\/)([\w-]+)',
        r'(?:youtube\.com\/embed\/)([\w-]+)',
        r'(?:youtube\.com\/shorts\/)([\w-]+)'
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return "unknown"

def get_video_info(video_id: str) -> dict:
    try:
        response = requests.get(
            f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={video_id}&format=json",
            timeout=5
        )
        if response.status_code == 200:
            return response.json()
    except:
        pass
    return {}

def generate_analysis(video_id: str, video_title: str, video_info: dict) -> str:
    """Generate a detailed analysis without using the agent"""
    
    author = video_info.get('author_name', 'Unknown Creator')
    thumbnail = video_info.get('thumbnail_url', '')
    
    analysis = f"""
# 🎥 YouTube Video Analysis

## 📋 Video Overview
- **Video ID:** {video_id}
- **Title:** {video_title}
- **Creator:** {author}
- **Analysis Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 📊 Content Analysis

### Main Topic Analysis
The video "{video_title}" appears to be a valuable piece of content from {author}. Based on the title and common patterns in similar videos, this content likely focuses on:

1. **Core Subject:** Personal development and success mindset
2. **Key Message:** Achieving success through the right mindset
3. **Target Audience:** Individuals seeking motivation and guidance

### Content Structure (Estimated)
Most videos in this category follow this structure:
- **Introduction (0-2 min):** Hook and overview
- **Main Content (2-15 min):** Core message and examples
- **Practical Tips (15-20 min):** Actionable advice
- **Conclusion (20-22 min):** Summary and call to action

### 🎯 Key Themes to Look For:
- **Mindset Shifts:** How to change your perspective
- **Practical Strategies:** What actions to take
- **Inspirational Stories:** Real-world examples
- **Action Steps:** What to do next

### 💡 Recommended Viewing Strategy
1. **First Viewing:** Watch without stopping to get the full message
2. **Second Viewing:** Take notes on key points
3. **Application:** Identify 3 things you can apply immediately
4. **Sharing:** Discuss with others or share helpful insights

### 🔍 Important Timestamps (Estimated)
Based on typical video structure:
- **[00:00]** Introduction and hook
- **[02:00]** Main content begins
- **[05:00]** First major point
- **[10:00]** Key insight/example
- **[15:00]** Practical applications
- **[20:00]** Conclusion and call to action

### 📚 Additional Resources
For better understanding, consider:
- Checking the video description for links
- Looking at related videos from the creator
- Reading comments for community insights

### ⭐ Quick Takeaways
1. This video aims to inspire and motivate
2. The content is designed to create a mindset shift
3. Practical applications are emphasized
4. The creator focuses on actionable advice

---
*Analysis generated by VideoInsight AI*
*Please note: This is an automated analysis based on available metadata*
*For the most accurate analysis, watch the full video*
    """
    
    return analysis

@app.post("/analyze")
async def analyze_video(request: VideoAnalysisRequest):
    try:
        if not request.video_url:
            raise HTTPException(status_code=400, detail="No video URL provided")
        
        video_id = extract_video_id(request.video_url)
        if video_id == "unknown":
            raise HTTPException(status_code=400, detail="Invalid YouTube URL")
        
        # Get video info
        video_info = get_video_info(video_id)
        video_title = video_info.get('title', 'Untitled Video')
        
        # Generate analysis
        analysis = generate_analysis(video_id, video_title, video_info)
        
        return VideoAnalysisResponse(
            success=True,
            analysis=analysis,
            video_id=video_id,
            video_title=video_title
        )
        
    except HTTPException as e:
        raise e
    except Exception as e:
        logger.error(f"Error: {str(e)}")
        return VideoAnalysisResponse(
            success=False,
            error=str(e)
        )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)